# Generated by Django 4.0.1 on 2022-01-17 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appFolder', '0007_rename_hospital_address1_hospital_hospital_address1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoModel',
            fields=[
                ('info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appFolder.info')),
            ],
            bases=('appFolder.info',),
        ),
    ]
