# Generated by Django 4.0.1 on 2022-01-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFolder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='info_dateOfBirth',
            field=models.DateField(help_text='YYYY/MM/DD', verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='info',
            name='info_vaccine',
            field=models.CharField(choices=[('fd', 'First Dose'), ('bd', 'Booster Dose'), ('ad', 'Additional Dose')], max_length=2, verbose_name='vaccine'),
        ),
    ]
