# Generated by Django 4.0.1 on 2022-01-09 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFolder', '0002_alter_info_info_dateofbirth_alter_info_info_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='Hospital_zipcode',
            field=models.CharField(default='10001', max_length=11, validators=[django.core.validators.RegexValidator('^([0-9]{5}(?:-[0-9]{4})?$)', 'Must be 00000 or 00000-0000', 'This is code')], verbose_name='Hospital zipcode'),
        ),
        migrations.AlterField(
            model_name='info',
            name='info_zipCode',
            field=models.CharField(default='10001', max_length=11, validators=[django.core.validators.RegexValidator('^([0-9]{5}(?:-[0-9]{4})?$)', 'Must be 00000 or 00000-0000', 'This is code')], verbose_name='zipcode'),
        ),
    ]
