# Generated by Django 4.0.1 on 2022-02-25 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFolder', '0002_alter_hospital_hospital_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='info_firstName',
            field=models.CharField(default='unknown', max_length=40, verbose_name='firstName'),
        ),
        migrations.AddField(
            model_name='info',
            name='info_lastName',
            field=models.CharField(default='unknown', max_length=40, verbose_name='lastName'),
        ),
        migrations.AlterField(
            model_name='info',
            name='info_zipCode',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^([0-9]{5}(?:-[0-9]{4})?$)', 'Must be 00000 or 00000-0000', 'This is code')], verbose_name='zipcode'),
        ),
    ]
