# Generated by Django 4.0.1 on 2022-01-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFolder', '0003_alter_hospital_hospital_zipcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='info_vaccineType',
            field=models.CharField(choices=[('pf', 'pfizer'), ('js', 'janssen')], max_length=2, verbose_name='vaccine type'),
        ),
    ]
