# Generated by Django 4.0.1 on 2022-03-08 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFolder', '0003_info_info_firstname_info_info_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='info_hospital_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='appFolder.hospital'),
            preserve_default=False,
        ),
    ]
