# Generated by Django 4.0.1 on 2022-01-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFolder', '0004_alter_info_info_vaccinetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Hospital_vaccineType',
            field=models.CharField(choices=[('pf', 'pfizer'), ('js', 'janssen'), ('all', 'all')], default='pf', max_length=4, verbose_name='Hospital vaccineType'),
            preserve_default=False,
        ),
    ]
