# Generated by Django 4.0.1 on 2022-03-08 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFolder', '0004_info_info_hospital_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='info_hospital_id',
            field=models.ForeignKey(default='4000', on_delete=django.db.models.deletion.PROTECT, to='appFolder.hospital'),
        ),
    ]
