# Generated by Django 4.0.1 on 2022-01-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFolder', '0005_hospital_hospital_vaccinetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='Hospital_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Hospital name'),
        ),
    ]
