# Generated by Django 4.0.1 on 2022-01-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFolder', '0006_alter_hospital_hospital_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='Hospital_address1',
            new_name='hospital_address1',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='Hospital_address2',
            new_name='hospital_address2',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='Hospital_city',
            new_name='hospital_city',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='Hospital_name',
            new_name='hospital_name',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='Hospital_state',
            new_name='hospital_state',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='Hospital_vaccineType',
            new_name='hospital_vaccineType',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='Hospital_zipcode',
            new_name='hospital_zipcode',
        ),
    ]
