# Generated by Django 4.0.1 on 2022-03-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFolder', '0006_alter_info_info_hospital_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='info_state',
            field=models.CharField(default='NY', max_length=40, verbose_name='customer state'),
        ),
    ]
