# Generated by Django 4.0.1 on 2022-03-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFolder', '0008_info_created_at_info_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='info_vaccineType',
            field=models.CharField(choices=[('pf', 'pfizer'), ('js', 'janssen'), ('all', 'all')], max_length=3, verbose_name='vaccine type'),
        ),
    ]
